title:              Flaint Cloth
email:              fandomnesia@yahoo.com
description:        a clothing brand that combines a sense and integrity into a work of art design and fashion
author:             Ilham maulana
baseurl:            ""
url:                "https://impwriter.github.io"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
